[package]
name = "weather-bandit"
version = "0.1.0"
authors = ["Michael <michaelbrockus@gmail.com>"]
edition = "2018"
readme = "readme.md"
license = "Apache-2.0"
repository = "https://github.com/michaelbrockus/weather-bandit"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "weather-bandit"
path = "src/main.rs"

[lib]
name = "program"
path = "src/lib.rs"

[dependencies]
reqwest = "0.8.6"
serde_json = "1.0"
serde = "1.0.70"
serde_derive = "1.0.70"
time = "0.1.40"
url = "1.5.1"
