name: Mac OSX host system

on:
  push:
  pull_request:

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-python@v2.2.1
      with:
        python-version: '3.9.x'
    - run: cargo run

